version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_hn
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./custom_postgresql.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5432:5432"

volumes:
  postgres_data:
